openapi: 3.1.0
info:
  title: The Odds API
  version: "1.0"
  description: API for retrieving live NHL betting odds.
  contact:
    email: "support@example.com"
  termsOfService: "https://example.com/terms"
  privacyPolicy: "https://example.com/privacy"

servers:
  - url: https://api.the-odds-api.com/v4

components:
  schemas:
    OddsResponse:
      type: object
      properties:
        home_team:
          type: string
        away_team:
          type: string
        commence_time:
          type: string
        odds:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              outcomes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    price:
                      type: number
                    point:
                      type: number
                      nullable: true

paths:
  /sports/icehockey_nhl/odds:
    get:
      summary: Get current NHL odds
      operationId: getNhlOdds
      parameters:
        - name: apiKey
          in: query
          required: true
          schema:
            type: string
            example: "283e3940f5d0de060198132213feef1c"
          default: "283e3940f5d0de060198132213feef1c"
        - name: regions
          in: query
          required: true
          schema:
            type: string
            example: "us"
          default: "us"
        - name: markets
          in: query
          required: true
          schema:
            type: string
            example: "h2h,spreads,totals"
          default: "h2h,spreads,totals"
        - name: oddsFormat
          in: query
          required: false
          schema:
            type: string
            example: "american"
          default: "american"
      responses:
        "200":
          description: Successful response with NHL odds
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OddsResponse'
